### ISSUE TITLE
老哥你好,我发现一个问题

### ISSUE THREAD

**Issue by maoweifan** [ly641921791/knowledge-examples#1]
<dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
</dependency>
的1.0.1以上版本会引发java.lang.NoClassDefFoundError: com/alibaba/nacos/client/naming/utils/StringUtils
1.0.0版本能找到这个类

**Comment by ly641921791** [comment]
@maoweifan 如果你要使用1.0.1版本客户端，最好先排除1.0.0版本客户端jar，这个异常一般都是jar冲突导致的

**Comment by ly641921791** [comment]
@maoweifan 如果用了dubbo建议升级到最新版本
